"""describe the change

Revision ID: 2373c4119458
Revises: 
Create Date: 2026-08-19 19:03:09.115113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2373c4119458'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('age > 0 AND age < 130', name='check_age_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('sleep_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('sleep_duration_hours', sa.Float(), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=False),
    sa.Column('is_deep_sleep', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('record_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_device_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('heart_rate > 20 AND heart_rate < 220', name='check_heart_rate_range'),
    sa.CheckConstraint('sleep_duration_hours > 0 AND sleep_duration_hours < 24', name='check_sleep_duration_hours_range'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_readings_id'), 'sleep_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_readings_id'), table_name='sleep_readings')
    op.drop_table('sleep_readings')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
